import fs from 'fs';
import path from 'path';

const publicDir = path.join(process.cwd(), 'public');
const SITE_URL = 'https://kssmi.com';

if (!fs.existsSync(publicDir)) {
    fs.mkdirSync(publicDir, { recursive: true });
}

const currentDate = new Date().toISOString().split('T')[0];

const parseFrontmatter = (fileContent) => {
    const match = fileContent.match(/---\r?\n([\s\S]*?)\r?\n---/);
    if (!match || !match[1]) return null;

    const frontmatter = match[1];

    const getValue = (key) => {
        const regex = new RegExp(`${key}:\\s*(.*)`);
        const m = frontmatter.match(regex);
        return m ? m[1].replace(/['"]/g, '').trim() : null;
    };

    const getArray = (key) => {
        const regex = new RegExp(`${key}:\\s*\\[(.*?)\\]`);
        const m = frontmatter.match(regex);
        return m ? m[1].split(',').map(s => s.replace(/['"]/g, '').trim()) : null;
    };

    return {
        title: getValue('title'),
        description: getValue('description') || getValue('seoDescription'),
        slug: getValue('slug'),
        itemNo: getValue('itemNo'),
        categories: getArray('categories'),
        materials: getArray('materials'),
        serviceMode: getArray('serviceMode'),
        moq: getValue('moq'),
        pubDate: getValue('pubDate')
    };
};

const langData = {};

const processCollection = (collectionName, titlePathPattern) => {
    const dir = path.join(process.cwd(), `src/content/${collectionName}`);
    if (!fs.existsSync(dir)) return;

    const getAllFiles = (dirPath, arrayOfFiles = []) => {
        const files = fs.readdirSync(dirPath);
        files.forEach(file => {
            const absolutePath = path.join(dirPath, file);
            if (fs.statSync(absolutePath).isDirectory()) {
                arrayOfFiles = getAllFiles(absolutePath, arrayOfFiles);
            } else if (file.endsWith('.md') || file.endsWith('.mdx')) {
                arrayOfFiles.push(absolutePath);
            }
        });
        return arrayOfFiles;
    };

    const files = getAllFiles(dir);

    files.forEach(filePath => {
        const file = path.basename(filePath);
        const content = fs.readFileSync(filePath, 'utf-8');
        const data = parseFrontmatter(content);

        if (data && data.title) {
            const langMatch = file.match(/\.([a-z]{2})\.mdx?$/);
            const lang = langMatch ? langMatch[1] : 'en';

            if (!langData[lang]) {
                langData[lang] = { products: [], landing: [], blog: [] };
            }

            const urlPrefix = lang === 'en' ? '' : `/${lang}`;
            const slugPart = data.slug ? data.slug.replace(/\/$/, '') : file.replace(/\.[a-z]{2}\.mdx?$/, '').replace(/\.md$/, '');
            const urlPathParams = titlePathPattern ? `${titlePathPattern}/` : '';
            const url = `${SITE_URL}${urlPrefix}/${urlPathParams}${slugPart}`;

            const header = data.itemNo ? `- ${data.title} (${data.itemNo})` : `- ${data.title}`;

            let entry = `${header} | ${url}\n`;
            if (data.categories) entry += `  > Categories: ${data.categories.join(', ')}\n`;
            if (data.materials) entry += `  > Materials: ${data.materials.join(', ')}\n`;
            if (data.serviceMode) entry += `  > Service Modes: ${data.serviceMode.join(', ')}\n`;
            if (data.moq) entry += `  > MOQ: ${data.moq}\n`;
            if (data.pubDate) entry += `  > Published: ${data.pubDate}\n`;
            entry += `\n`;

            if (langData[lang][collectionName] !== undefined) {
                langData[lang][collectionName].push(entry);
            }
        }
    });
};

processCollection('landing', 'landing');
processCollection('products', 'product');
processCollection('blog', 'blog');

const translations = {
    en: {
        guide: "Large Language Model Guide",
        core: "Core Pages", coreDesc: "Primary navigation and company information.",
        products: "Products", productsDesc: "Catalog of our premium B2B sunglasses and eyewear frames.",
        landing: "Landing Pages", landingDesc: "Product collections, material guides, and marketing pages.",
        blog: "Blogs", blogDesc: "Industry insights, news, and editorial articles.",
        explore: "To explore our %LANG% content, please follow the specialized directories below:",
        generated: "Generated by Kssmi Eyewear",
        home: "Homepage", about: "About Us", contact: "Contact"
    },
    zh: {
        guide: "大语言模型指南",
        core: "核心页面", coreDesc: "主要导航和公司信息。",
        products: "产品", productsDesc: "我们的优质 B2B 太阳镜和眼镜架目录。",
        landing: "着陆页", landingDesc: "产品系列、材料指南和营销页面。",
        blog: "博客", blogDesc: "行业洞察、新闻和社论文章。",
        explore: "要探索我们的 %LANG% 内容，请按照以下专门的目录进行：",
        generated: "由 Kssmi Eyewear 生成",
        home: "主页", about: "关于我们", contact: "联系我们"
    },
    de: {
        guide: "Leitfaden für große Sprachmodelle",
        core: "Kernseiten", coreDesc: "Primäre Navigation und Unternehmensinformationen.",
        products: "Produkte", productsDesc: "Katalog unserer Premium-B2B-Sonnenbrillen und Brillenfassungen.",
        landing: "Zielseiten", landingDesc: "Produktkollektionen, Materialleitfäden und Marketingseiten.",
        blog: "Blogs", blogDesc: "Branchenerkenntnisse, Neuigkeiten und redaktionelle Artikel.",
        explore: "Um unsere %LANG%-Inhalte zu erkunden, folgen Sie bitte den unten stehenden speziellen Verzeichnissen:",
        generated: "Erstellt von Kssmi Eyewear",
        home: "Startseite", about: "Über uns", contact: "Kontakt"
    },
    es: {
        guide: "Guía de modelos de lenguaje grande",
        core: "Páginas principales", coreDesc: "Navegación principal e información de la empresa.",
        products: "Productos", productsDesc: "Catálogo de nuestras gafas de sol B2B premium y monturas.",
        landing: "Páginas de aterrizaje", landingDesc: "Colecciones de productos, guías de materiales y páginas de marketing.",
        blog: "Blogs", blogDesc: "Perspectivas de la industria, noticias y artículos editoriales.",
        explore: "Para explorar nuestro contenido en %LANG%, siga los directorios especializados a continuación:",
        generated: "Generado por Kssmi Eyewear",
        home: "Inicio", about: "Sobre nosotros", contact: "Contacto"
    },
    fr: {
        guide: "Guide des grands modèles linguistiques",
        core: "Pages principales", coreDesc: "Navigation principale et informations sur l'entreprise.",
        products: "Produits", productsDesc: "Catalogue de nos lunettes de soleil B2B haut de gamme et montures.",
        landing: "Pages de destination", landingDesc: "Collections de produits, guides des matériaux et pages marketing.",
        blog: "Blogs", blogDesc: "Aperçus de l'industrie, actualités et articles éditoriaux.",
        explore: "Pour explorer notre contenu en %LANG%, veuillez suivre les répertoires spécialisés ci-dessous :",
        generated: "Généré par Kssmi Eyewear",
        home: "Accueil", about: "À propos", contact: "Contact"
    },
    ar: {
        guide: "دليل نماذج اللغة الكبيرة",
        core: "الصفحات الأساسية", coreDesc: "التنقل الأساسي ومعلومات الشركة.",
        products: "المنتجات", productsDesc: "كتالوج نظاراتنا الشمسية B2B وإطارات النظارات الفاخرة.",
        landing: "الصفحات المقصودة", landingDesc: "مجموعات المنتجات وأدلة المواد وصفحات التسويق.",
        blog: "المدونات", blogDesc: "رؤى الصناعة والأخبار والمقالات التحريرية.",
        explore: "لاستكشاف محتوانا بـ %LANG%، يرجى اتباع الأدلة المتخصصة أدناه:",
        generated: "تم الإنشاء بواسطة Kssmi Eyewear",
        home: "الصفحة الرئيسية", about: "من نحن", contact: "اتصل بنا"
    },
    hi: {
        guide: "लार्ज लैंग्वेज मॉडल गाइड",
        core: "मुख्य पृष्ठ", coreDesc: "प्राथमिक नेविगेशन और कंपनी की जानकारी।",
        products: "उत्पाद", productsDesc: "हमारे प्रीमियम B2B धूप का चश्मा और चश्मा फ्रेम की सूची।",
        landing: "लैंडिंग पृष्ठ", landingDesc: "उत्पाद संग्रह, सामग्री गाइड और विपणन पृष्ठ।",
        blog: "ब्लॉग", blogDesc: "उद्योग अंतर्दृष्टि, समाचार और संपादकीय लेख।",
        explore: "हमारी %LANG% सामग्री का पता लगाने के लिए, कृपया नीचे दी गई विशेष निर्देशिकाओं का पालन करें:",
        generated: "Kssmi Eyewear द्वारा निर्मित",
        home: "होमपेज", about: "हमारे बारे में", contact: "संपर्क करें"
    },
    it: {
        guide: "Guida ai modelli linguistici di grandi dimensioni",
        core: "Pagine principali", coreDesc: "Navigazione primaria e informazioni aziendali.",
        products: "Prodotti", productsDesc: "Catalogo dei nostri occhiali da sole e montature B2B premium.",
        landing: "Pagine di atterraggio", landingDesc: "Collezioni di prodotti, guide ai materiali e pagine di marketing.",
        blog: "Blog", blogDesc: "Approfondimenti del settore, notizie e articoli editoriali.",
        explore: "Per esplorare i nostri contenuti in %LANG%, segui le directory specializzate di seguito:",
        generated: "Generato da Kssmi Eyewear",
        home: "Home page", about: "Chi siamo", contact: "Contattaci"
    },
    ja: {
        guide: "大規模言語モデルガイド",
        core: "コアページ", coreDesc: "主要なナビゲーションと企業情報。",
        products: "製品", productsDesc: "当社のプレミアムB2Bサングラスとメガネフレームのカタログ。",
        landing: "ランディングページ", landingDesc: "製品コレクション、素材ガイド、マーケティングページ。",
        blog: "ブログ", blogDesc: "業界の洞察、ニュース、編集記事。",
        explore: "当社の %LANG% コンテンツを検索するには、以下の専門ディレクトリに従ってください：",
        generated: "Kssmi Eyewear によって生成",
        home: "ホームページ", about: "私たちについて", contact: "お問い合わせ"
    },
    jv: {
        guide: "Pandhuan Model Basa Gedhe",
        core: "Kaca Utama", coreDesc: "Pandhu arah utama lan informasi perusahaan.",
        products: "Produk", productsDesc: "Katalog kacamata ireng B2B premium lan bingkai kacamata.",
        landing: "Kaca kebangkrutan", landingDesc: "Koleksi produk, pandhuan materi, lan kaca pemasaran.",
        blog: "Blog", blogDesc: "Wawasan industri, warta, lan artikel editorial.",
        explore: "Kanggo njelajah konten %LANG% kita, tututi direktori khusus ing ngisor iki:",
        generated: "Digawe dening Kssmi Eyewear",
        home: "Kaca Ngarep", about: "Babagan Kita", contact: "Hubungi Kita"
    },
    ko: {
        guide: "대형 언어 모델 가이드",
        core: "핵심 페이지", coreDesc: "기본 탐색 및 회사 정보.",
        products: "제품", productsDesc: "프리미엄 B2B 선글라스 및 안경테 카탈로그.",
        landing: "랜딩 페이지", landingDesc: "제품 컬렉션, 소재 가이드 및 마케팅 페이지.",
        blog: "블로그", blogDesc: "산업 통찰력, 뉴스 및 편집 기사.",
        explore: "%LANG% 콘텐츠를 탐색하려면 아래의 전문 디렉토리를 따르십시오.",
        generated: "Kssmi Eyewear 제작",
        home: "홈페이지", about: "회사 소개", contact: "문의하기"
    },
    ms: {
        guide: "Panduan Model Bahasa Besar",
        core: "Halaman Utama", coreDesc: "Navigasi utama dan maklumat syarikat.",
        products: "Produk", productsDesc: "Katalog cermin mata hitam B2B premium dan bingkai cermin mata kami.",
        landing: "Halaman Pendaratan", landingDesc: "Koleksi produk, panduan bahan dan halaman pemasaran.",
        blog: "Blog", blogDesc: "Wawasan industri, berita dan artikel editorial.",
        explore: "Untuk meneroka kandungan %LANG% kami, sila ikuti direktori khusus di bawah:",
        generated: "Dihasilkan oleh Kssmi Eyewear",
        home: "Laman Utama", about: "Tentang Kami", contact: "Hubungi Kami"
    },
    pt: {
        guide: "Guia de Grandes Modelos de Linguagem",
        core: "Páginas Principais", coreDesc: "Navegação primária e informações da empresa.",
        products: "Produtos", productsDesc: "Catálogo de nossos óculos de sol e armações B2B premium.",
        landing: "Páginas de Destino", landingDesc: "Coleções de produtos, guias de materiais e páginas de marketing.",
        blog: "Blogs", blogDesc: "Insights do setor, notícias e artigos editoriais.",
        explore: "Para explorar nosso conteúdo em %LANG%, siga os diretórios especializados abaixo:",
        generated: "Gerado por Kssmi Eyewear",
        home: "Página Inicial", about: "Sobre Nós", contact: "Contato"
    },
    ru: {
        guide: "Руководство по большим языковым моделям",
        core: "Основные страницы", coreDesc: "Основная навигация и информация о компании.",
        products: "Продукты", productsDesc: "Каталог наших премиальных B2B солнцезащитных очков и оправ.",
        landing: "Целевые страницы", landingDesc: "Коллекции продуктов, руководства по материалам и маркетинговые страницы.",
        blog: "Блоги", blogDesc: "Отраслевые идеи, новости и редакционные статьи.",
        explore: "Чтобы изучить наш контент на %LANG%, пожалуйста, следуйте специализированным каталогам ниже:",
        generated: "Создано Kssmi Eyewear",
        home: "Главная страница", about: "О нас", contact: "Связаться с нами"
    },
    tg: {
        guide: "Роҳнамои моделҳои бузурги забонӣ",
        core: "Саҳифаҳои асосӣ", coreDesc: "Навигатсияи ибтидоӣ ва маълумоти ширкат.",
        products: "Маҳсулот", productsDesc: "Каталоги айнакҳои офтобии премиум B2B ва чорчӯбаи айнакҳои мо.",
        landing: "Саҳифаҳои фуруд", landingDesc: "Маҷмӯаҳои маҳсулот, дастурҳои мавод ва саҳифаҳои маркетингӣ.",
        blog: "Блогҳо", blogDesc: "Фаҳмишҳои соҳа, ахбор ва мақолаҳои таҳрирӣ.",
        explore: "Барои омӯхтани мундариҷаи %LANG%-и мо, лутфан ба директорияҳои махсуси зерин пайравӣ кунед:",
        generated: "Аз ҷониби Kssmi Eyewear тавлид шудааст",
        home: "Саҳифаи асосӣ", about: "Дар бораи мо", contact: "Бо мо тамос гиред"
    },
    tr: {
        guide: "Büyük Dil Modeli Kılavuzu",
        core: "Ana Sayfalar", coreDesc: "Birincil gezinme ve şirket bilgileri.",
        products: "Ürünler", productsDesc: "Premium B2B güneş gözlüklerimiz ve gözlük çerçevelerimiz kataloğu.",
        landing: "Açılış Sayfaları", landingDesc: "Ürün koleksiyonları, malzeme kılavuzları ve pazarlama sayfaları.",
        blog: "Bloglar", blogDesc: "Sektörel içgörüler, haberler ve editoryal makaleler.",
        explore: "%LANG% İçeriğimizi keşfetmek için lütfen aşağıdaki özel dizinleri takip edin:",
        generated: "Kssmi Eyewear tarafından oluşturuldu",
        home: "Ana Sayfa", about: "Hakkımızda", contact: "İletişim"
    },
    vi: {
        guide: "Hướng dẫn Mô hình Ngôn ngữ Lớn",
        core: "Trang Cốt Lõi", coreDesc: "Điều hướng chính và thông tin công ty.",
        products: "Sản phẩm", productsDesc: "Danh mục kính râm B2B cao cấp và gọng kính của chúng tôi.",
        landing: "Trang Đích", landingDesc: "Bộ sưu tập sản phẩm, hướng dẫn chất liệu và trang tiếp thị.",
        blog: "Blog", blogDesc: "Sự hiểu biết sâu sắc về ngành, tin tức và bài báo biên tập.",
        explore: "Để khám phá nội dung %LANG% của chúng tôi, vui lòng theo các thư mục chuyên dụng dưới đây:",
        generated: "Được tạo bởi Kssmi Eyewear",
        home: "Trang chủ", about: "Về chúng tôi", contact: "Liên hệ"
    }
};

// Generate files for each language
Object.keys(langData).forEach(lang => {
    const langDir = path.join(publicDir, lang);
    if (!fs.existsSync(langDir)) {
        fs.mkdirSync(langDir, { recursive: true });
    }

    const t = translations[lang] || translations['en'];
    let localLangName = lang.toUpperCase();
    try {
        localLangName = new Intl.DisplayNames([lang], { type: 'language' }).of(lang);
        // Capitalize first letter for some languages that might return lowercase
        localLangName = localLangName.charAt(0).toUpperCase() + localLangName.slice(1);
    } catch (e) { }

    const exploreText = t.explore.replace('%LANG%', localLangName);

    const langUrlPrefix = lang === 'en' ? '' : `/${lang}`;
    const baseUrl = `${SITE_URL}${langUrlPrefix}`;
    const llmsBaseUrl = `${SITE_URL}/${lang}`;

    // 1. llms-core.txt
    const coreContent = `\uFEFF# Kssmi - ${t.core} (${localLangName})\n\n${t.coreDesc}\n\n- ${t.home} | ${baseUrl}/\n- ${t.about} | ${baseUrl}/about-us/\n- ${t.contact} | ${baseUrl}/contact/\n`;
    fs.writeFileSync(path.join(langDir, 'llms-core.txt'), coreContent, 'utf-8');

    // 2. llms-products.txt
    const productsContent = `\uFEFF# Kssmi - ${t.products} (${localLangName})\n\n${t.productsDesc}\n\n${langData[lang].products.join('')}`;
    fs.writeFileSync(path.join(langDir, 'llms-products.txt'), productsContent, 'utf-8');

    // 3. llms-landing.txt
    const landingContent = `\uFEFF# Kssmi - ${t.landing} (${localLangName})\n\n${t.landingDesc}\n\n${langData[lang].landing.join('')}`;
    fs.writeFileSync(path.join(langDir, 'llms-landing.txt'), landingContent, 'utf-8');

    // 4. llms-blogs.txt
    const blogContent = `\uFEFF# Kssmi - ${t.blog} (${localLangName})\n\n${t.blogDesc}\n\n${langData[lang].blog.join('')}`;
    fs.writeFileSync(path.join(langDir, 'llms-blogs.txt'), blogContent, 'utf-8');

    // 5. Language Index (llms.txt) for this specific language
    const langIndexContent = `\uFEFF# Kssmi ${t.guide} - ${localLangName}
Date: ${currentDate}

${exploreText}

## ${t.core} (${t.coreDesc})
- ${llmsBaseUrl}/llms-core.txt

## ${t.products} (${t.productsDesc})
- ${llmsBaseUrl}/llms-products.txt

## ${t.landing} (${t.landingDesc})
- ${llmsBaseUrl}/llms-landing.txt

## ${t.blog} (${t.blogDesc})
- ${llmsBaseUrl}/llms-blogs.txt

*${t.generated}*
`;

    fs.writeFileSync(path.join(langDir, 'llms.txt'), langIndexContent, 'utf-8');
});

// Finally, generate the Global Router at public/llms.txt
let globalContent = `\uFEFF# Kssmi Large Language Model Guide
Date: ${currentDate}

Kssmi is a leading B2B handmade eyewear and sunglasses manufacturer based in Guangdong, China, operational since 2003. We specialize in producing high-quality, ethically produced handcrafted eyewear and sunglasses for global brands, using premium and sustainable materials like bio-acetate and recycled metals. Our craftsmanship combines traditional techniques with modern technology to create unique frames that mass production cannot replicate.

This document serves as an index to guide AI agents to our language-specific content directories.

## Language Maps
To explore our site optimally, please follow the directory for your desired language:

`;

// Use Intl.DisplayNames to dynamically support any new language added in the future
const languageNames = new Intl.DisplayNames(['en'], { type: 'language' });

Object.keys(langData).sort().forEach(lang => {
    let langName = lang.toUpperCase();
    try {
        langName = languageNames.of(lang);
    } catch (e) {
        // Fallback to uppercase code if Intl fails for some reason
    }
    globalContent += `- ${langName} Language index [${lang}]: https://kssmi.com/${lang}/llms.txt\n`;
});

globalContent += `
Company Legal Information & Sitemap:
- sitemap | https://kssmi.com/sitemap-index.xml

*Generated by Kssmi Eyewear*
`;

fs.writeFileSync(path.join(publicDir, 'llms.txt'), globalContent, 'utf-8');

console.log('✅ Generated split llms tree architecture inside public/ directory successfully!');
