<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/private/short-links-tool.php';
kssmi_admin_require_trusted_proxy(); kssmi_short_links_session();
header("Content-Security-Policy: default-src 'self'; frame-ancestors 'none'; base-uri 'none'; form-action 'self'"); header('X-Robots-Tag: noindex, nofollow'); header('Cache-Control: no-store, private');
$message = '';
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if (!kssmi_admin_csrf_valid($_POST['csrf_token'] ?? null, 'short_links_tool_csrf')) { $message = 'Security check failed.'; }
    elseif (isset($_POST['logout'])) { unset($_SESSION['short_links_tool_auth'], $_SESSION['short_links_tool_email'], $_SESSION['short_links_tool_admin']); $message = 'Signed out.'; }
    elseif (isset($_POST['login']) && kssmi_short_links_login((string)($_POST['email'] ?? ''), (string)($_POST['password'] ?? ''))) { header('Location: /short-links'); exit; }
    else { $message = 'Invalid email or password.'; }
}
$identity = kssmi_short_links_identity(); $csrf = kssmi_short_links_csrf(); $reset = (string)($_GET['reset'] ?? '');
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>KSSMI Short Links</title><style>body{font:16px system-ui,sans-serif;max-width:1100px;margin:40px auto;padding:0 20px;color:#222}input,button{padding:9px;margin:4px}table{border-collapse:collapse;width:100%}td,th{border-bottom:1px solid #ddd;padding:8px;text-align:left}.msg{padding:10px;background:#fff3cd}.box{border:1px solid #ddd;border-radius:8px;padding:18px;margin:16px 0}</style></head><body><h1>KSSMI Short Links</h1><?php if ($message): ?><p class="msg"><?php echo htmlspecialchars($message); ?></p><?php endif; ?>
<?php if (!$identity): ?><div class="box"><h2>Sign in</h2><form method="post"><input type="hidden" name="csrf_token" value="<?php echo htmlspecialchars($csrf); ?>"><input name="email" type="email" placeholder="Email" required><input name="password" type="password" placeholder="Password" required><button name="login" value="1">Sign in</button></form><p>Forgot your password? Use the reset form below.</p><form method="post" action="/api/short-links-reset.php"><input type="hidden" name="csrf_token" value="<?php echo htmlspecialchars($csrf); ?>"><input type="hidden" name="action" value="request"><input name="email" type="email" placeholder="Account email" required><button>Send reset email</button></form></div>
<?php if ($reset !== ''): ?><div class="box"><h2>Set a new password</h2><form method="post" action="/api/short-links-reset.php"><input type="hidden" name="csrf_token" value="<?php echo htmlspecialchars($csrf); ?>"><input type="hidden" name="action" value="confirm"><input type="hidden" name="token" value="<?php echo htmlspecialchars($reset); ?>"><input name="password" type="password" minlength="10" maxlength="128" placeholder="New password" required><button>Save password</button></form></div><?php endif; ?>
<?php else: ?><p>Signed in as <strong><?php echo htmlspecialchars($identity['email']); ?></strong> <?php if ($identity['admin']) echo '(admin)'; ?><form method="post" style="display:inline"><input type="hidden" name="csrf_token" value="<?php echo htmlspecialchars($csrf); ?>"><button name="logout" value="1">Sign out</button></form></p><div class="box"><h2>Create a short link</h2><form id="create"><input name="target_url" type="url" placeholder="https://example.com/..." size="55" required><input name="label" placeholder="Label"><input name="campaign" placeholder="Campaign"><input name="recipient_ref" placeholder="Recipient"><button>Create</button></form><p id="result"></p></div><div class="box"><h2>Your links<?php if($identity['admin']) echo ' (all accounts)'; ?></h2><input id="search" placeholder="Search"><button onclick="load()">Search</button><table><thead><tr><th>Code</th><th>Target</th><th>By</th><th>Opens</th><th>Actions</th></tr></thead><tbody id="rows"></tbody></table></div><script>const csrf=<?php echo json_encode($csrf); ?>;async function api(action,data={}){let r=await fetch('/api/short-links-tool.php',{method:'POST',headers:{'Content-Type':'application/json','Origin':location.origin,'Sec-Fetch-Site':'same-origin'},body:JSON.stringify({action,csrf_token:csrf,...data})});let b=await r.json();if(!r.ok)throw Error(b.error||'Request failed');return b}async function load(){try{let b=await api('list',{search:document.getElementById('search').value});document.getElementById('rows').innerHTML=b.rows.map(x=>`<tr><td><a href="/${x.code}">${x.code}</a></td><td>${x.target_url}</td><td>${x.created_by||''}</td><td>${x.opens||0}</td><td><button onclick="del(${x.id},'${x.code}')">Delete</button></td></tr>`).join('')}catch(e){alert(e.message)}}async function del(id,code){if(!confirm('Delete '+code+'?'))return;try{await api('permanent-delete',{id,confirmation:'DELETE '+code});load()}catch(e){alert(e.message)}}document.getElementById('create').onsubmit=async e=>{e.preventDefault();let d=Object.fromEntries(new FormData(e.target));try{let x=await api('destination',{target_url:d.target_url});let id=x.destination.id;let y=await api('distribution',{destination_id:id,label:d.label,campaign:d.campaign,recipient_ref:d.recipient_ref});document.getElementById('result').textContent='Created: https://kssmi.com/'+y.link.code;load()}catch(e){document.getElementById('result').textContent=e.message}};load();</script><?php endif; ?></body></html>
