<?php
declare(strict_types=1);
require_once dirname(__DIR__, 2) . '/private/short-links-tool.php';
kssmi_admin_require_trusted_proxy(); kssmi_short_links_session();
header('Content-Type: text/html; charset=UTF-8'); header('Cache-Control: no-store, private'); header('X-Robots-Tag: noindex, nofollow');
if ($_SERVER['REQUEST_METHOD'] !== 'POST' || !kssmi_short_links_origin_ok() || !kssmi_admin_csrf_valid($_POST['csrf_token'] ?? null, 'short_links_tool_csrf')) { http_response_code(403); echo 'Invalid request.'; exit; }
$action=(string)($_POST['action']??''); $path=dirname(__DIR__,2).'/private/short-links-reset-tokens.json'; $tokens=is_file($path)?json_decode((string)file_get_contents($path),true):[]; if(!is_array($tokens))$tokens=[]; $now=time(); foreach($tokens as $key=>$row)if(($row['expires']??0)<=$now)unset($tokens[$key]);
if($action==='request') { $email=strtolower(trim((string)($_POST['email']??''))); $users=kssmi_short_links_users(); if(isset($users[$email])&&str_ends_with($email,KSSMI_SHORT_LINK_EMAIL_DOMAIN)){ $token=bin2hex(random_bytes(32));$tokens[$token]=['email'=>$email,'expires'=>$now+3600];kssmi_admin_atomic_write($path,json_encode($tokens,JSON_UNESCAPED_SLASHES),0600);kssmi_short_links_send_reset($email,$token); } echo 'If that account exists, a reset email has been sent.'; exit; }
if($action==='confirm') { $token=(string)($_POST['token']??'');$new=(string)($_POST['password']??'');if(!preg_match('/^[a-f0-9]{64}$/',$token)||strlen($new)<10||strlen($new)>128||!isset($tokens[$token])){http_response_code(422);echo'Invalid or expired reset.';exit;} $users=kssmi_short_links_users();$email=$tokens[$token]['email'];if(!isset($users[$email])){http_response_code(422);echo'Invalid or expired reset.';exit;}$users[$email]['hash']=password_hash($new,PASSWORD_DEFAULT);if(!kssmi_short_links_write_users($users)){http_response_code(500);echo'Password could not be saved.';exit;}unset($tokens[$token]);kssmi_admin_atomic_write($path,json_encode($tokens,JSON_UNESCAPED_SLASHES),0600);echo'Password reset. You can now sign in.';exit;} http_response_code(400);echo'Unknown action.';
