export interface OrderProductionCopy {
  eyebrow: string;
  title: string;
  intro: string;
  routesTitle: string;
  readyTitle: string;
  readyBody: string;
  customTitle: string;
  customBody: string;
  optionsTitle: string;
  optionsBody: string;
  packaging: string;
  processTitle: string;
  processSteps: string[];
  processNote: string;
  moqTimingTitle: string;
  standardMoq: string;
  colorSplit: string;
  tr90Moq: string;
  leadTimesTitle: string;
  readyLabel: string;
  readyLogoLabel: string;
  renderingLabel: string;
  customSampleLabel: string;
  bulkLabel: string;
  workingDays: string;
  timingNote: string;
  termsTitle: string;
  paymentTitle: string;
  paymentBody: string;
  samplesToolingTitle: string;
  creditBody: string;
  toolingBody: string;
  deliveryTitle: string;
  deliveryBody: string;
  quoteTitle: string;
  quoteBody: string;
  reply: string;
}

export const orderProductionCta: Record<string, string> = {
  en: 'Start Your Custom Project',
  zh: '开始您的定制项目',
  it: 'Avvia il tuo progetto personalizzato',
  es: 'Inicie su proyecto personalizado',
  fr: 'Démarrez votre projet sur mesure',
  de: 'Starten Sie Ihr individuelles Projekt',
  pt: 'Inicie o seu projeto personalizado',
  ar: 'ابدأ مشروعك المخصص',
  ru: 'Начать индивидуальный проект',
  ja: 'カスタムプロジェクトを始める',
  tr: 'Özel projenizi başlatın',
  ko: '맞춤 프로젝트 시작하기',
  hi: 'अपना कस्टम प्रोजेक्ट शुरू करें',
  vi: 'Bắt đầu dự án tùy chỉnh',
  jv: 'Miwiti proyek kustom',
  ms: 'Mulakan projek tersuai anda',
  tg: 'Лоиҳаи фармоишии худро оғоз кунед',
};

export const orderProductionCopy: Record<string, OrderProductionCopy> = {
  en: {
    eyebrow: 'Private-Label Project Guide',
    title: 'From Sample to Production',
    intro: 'Start with an existing Kssmi model or develop eyewear from your own idea. See what can be customized, how approval works and what we need to begin.',
    routesTitle: 'Two Ways to Start',
    readyTitle: 'Ready-Stock Sample',
    readyBody: 'Supplied in its original materials, colors, lenses and specifications. A standard logo can be added for {logoFee} per model; no other ready-stock details can be changed.',
    customTitle: 'Fully Custom Development',
    customBody: 'Modify an existing model or start from a sketch, photo, AI-generated concept, physical sample or complete technical drawing.',
    optionsTitle: 'What Can Be Customized?',
    optionsBody: 'Frame materials, colors and dimensions; lens materials, tints, coatings and functions; logo method and placement; hinges, hardware, nose pads, temple tips, structural details, molds and tooling.',
    packaging: 'We specialize in eyewear manufacturing and do not manufacture retail packaging.',
    processTitle: 'How Custom Development Works',
    processSteps: ['Send your idea', 'Engineering review & quotation', '2D rendering & confirmation', 'Physical sample', 'Sample approval', 'Bulk production & quality control', 'Pre-shipment review & approval', 'Door-to-door shipment'],
    processNote: 'Up to {revisions} 2D-rendering revision rounds are included. Changes requested after the physical sample is completed may require additional development or tooling fees.',
    moqTimingTitle: 'MOQ & Typical Lead Times',
    standardMoq: 'Most materials: {standardMoq} PCS per model',
    colorSplit: 'Up to {colors} colors, minimum {perColor} PCS per color',
    tr90Moq: 'TR90: {tr90Moq} PCS per model',
    leadTimesTitle: 'Typical lead times',
    readyLabel: 'Ready-stock sample',
    readyLogoLabel: 'Ready-stock sample with logo',
    renderingLabel: '2D rendering',
    customSampleLabel: 'Fully custom sample',
    bulkLabel: 'Bulk production',
    workingDays: 'working days',
    timingNote: 'Custom-sample timing begins after 2D-rendering approval. Bulk timing begins after sample approval and receipt of the {deposit}% deposit. Actual timing may vary by materials, complexity, custom components and production capacity.',
    termsTitle: 'Commercial Terms & Worldwide Delivery',
    paymentTitle: 'Payment',
    paymentBody: 'Samples require {samplePayment}% payment in advance. Bulk orders require a {deposit}% T/T deposit, with the balance paid before shipment.',
    samplesToolingTitle: 'Samples & Tooling',
    creditBody: 'The {readyPrice} ready-stock sample fee and {customMin}–{customMax} fully custom sample fee are fully credited toward a bulk order for the same model when its MOQ is met. The {logoFee} logo fee, shipping and taxes are not credited.',
    toolingBody: 'Customer-paid molds and tooling belong to the customer. Design changes requiring new tooling are quoted separately.',
    deliveryTitle: 'Delivery',
    deliveryBody: 'We ship worldwide via DHL or work with your nominated freight forwarder. Freight, duties and taxes are quoted separately.',
    quoteTitle: 'Ready to Discuss Your Eyewear Project?',
    quoteBody: 'Send your preferred material, design or reference images and customization requirements. Include the product SKU when modifying an existing Kssmi model.',
    reply: 'We normally reply within one business day.',
  },
  zh: {
    eyebrow: '自有品牌项目指南', title: '从样品到批量生产', intro: '您可以从 Kssmi 现有型号开始，也可以用自己的创意开发眼镜。这里说明可定制范围、确认流程以及项目启动所需资料。',
    routesTitle: '两种启动方式', readyTitle: '现货样品', readyBody: '按现有材料、颜色、镜片和规格提供。每个型号可加标准 Logo，费用为 {logoFee}；现货样品的其他内容不能修改。', customTitle: '全定制开发', customBody: '可以修改现有型号，也可以根据草图、照片、AI 概念图、实物样品或完整技术图纸重新开发。',
    optionsTitle: '哪些内容可以定制？', optionsBody: '镜框材料、颜色和尺寸；镜片材料、颜色、镀膜和功能；Logo 工艺和位置；铰链、五金、鼻托、脚套、结构细节以及模具和工装。', packaging: '我们专注于眼镜制造，不生产零售包装。',
    processTitle: '全定制开发流程', processSteps: ['提交创意或设计', '工程评估与报价', '2D 效果图与确认', '制作实物样品', '确认样品', '批量生产与质量检验', '发货前审核与确认', '门到门运输'], processNote: '包含最多 {revisions} 轮 2D 效果图修改。实物样品完成后提出的修改，可能产生额外开发费或模具费。',
    moqTimingTitle: 'MOQ 与参考交期', standardMoq: '大多数材料：每款 {standardMoq} PCS', colorSplit: '最多 {colors} 个颜色，每色至少 {perColor} PCS', tr90Moq: 'TR90：每款 {tr90Moq} PCS', leadTimesTitle: '参考交期', readyLabel: '现货样品', readyLogoLabel: '加 Logo 的现货样品', renderingLabel: '2D 效果图', customSampleLabel: '全定制样品', bulkLabel: '批量生产', workingDays: '个工作日', timingNote: '全定制样品交期从 2D 效果图确认后开始；大货交期从样品确认且收到 {deposit}% 定金后开始。实际时间可能因材料、复杂度、定制部件和产能而变化。',
    termsTitle: '商务条款与全球交付', paymentTitle: '付款方式', paymentBody: '样品须 {samplePayment}% 预付。大货采用 T/T 支付 {deposit}% 定金，余款在发货前付清。', samplesToolingTitle: '样品与模具', creditBody: '{readyPrice} 现货样品费和 {customMin}–{customMax} 全定制样品费，在同款大货达到 MOQ 时可全额抵扣；{logoFee} Logo 费、运费和税费不参与抵扣。', toolingBody: '由客户付费制作的模具和工装归客户所有。设计变更需要重新制作模具时另行报价。', deliveryTitle: '交付方式', deliveryBody: '我们全球发货，可使用 DHL 或配合客户指定货代。运费、关税和税费另行报价。', quoteTitle: '准备好讨论您的眼镜项目了吗？', quoteBody: '请发送首选材料、设计图或参考图片以及定制要求。修改 Kssmi 现有型号时，请同时提供产品 SKU。', reply: '我们通常会在一个工作日内回复。',
  },
  it: {
    eyebrow: 'Guida al progetto private label', title: 'Dal campione alla produzione', intro: 'Parti da un modello Kssmi esistente oppure sviluppa un occhiale dalla tua idea. Qui trovi personalizzazioni, approvazioni e dati necessari per iniziare.',
    routesTitle: 'Due modi per iniziare', readyTitle: 'Campione disponibile', readyBody: 'Fornito con materiali, colori, lenti e specifiche originali. È possibile aggiungere un logo standard a {logoFee} per modello; nessun altro dettaglio può essere modificato.', customTitle: 'Sviluppo completamente personalizzato', customBody: 'Modifica un modello esistente oppure parti da schizzo, foto, concept AI, campione fisico o disegno tecnico completo.',
    optionsTitle: 'Cosa si può personalizzare?', optionsBody: 'Materiali, colori e misure della montatura; materiali, tinte, trattamenti e funzioni delle lenti; metodo e posizione del logo; cerniere, minuteria, naselli, terminali, struttura, stampi e attrezzature.', packaging: 'Siamo specializzati nella produzione di occhiali e non produciamo packaging retail.',
    processTitle: 'Come funziona lo sviluppo', processSteps: ['Invio dell’idea', 'Valutazione tecnica e preventivo', 'Rendering 2D e conferma', 'Campione fisico', 'Approvazione del campione', 'Produzione e controllo qualità', 'Verifica e approvazione pre-spedizione', 'Consegna porta a porta'], processNote: 'Sono inclusi fino a {revisions} cicli di revisione del rendering 2D. Le modifiche dopo il campione fisico possono comportare costi aggiuntivi di sviluppo o attrezzaggio.',
    moqTimingTitle: 'MOQ e tempi indicativi', standardMoq: 'La maggior parte dei materiali: {standardMoq} PCS per modello', colorSplit: 'Fino a {colors} colori, minimo {perColor} PCS per colore', tr90Moq: 'TR90: {tr90Moq} PCS per modello', leadTimesTitle: 'Tempi indicativi', readyLabel: 'Campione disponibile', readyLogoLabel: 'Campione disponibile con logo', renderingLabel: 'Rendering 2D', customSampleLabel: 'Campione completamente personalizzato', bulkLabel: 'Produzione in serie', workingDays: 'giorni lavorativi', timingNote: 'Il tempo del campione personalizzato parte dall’approvazione del rendering 2D. La produzione parte dopo l’approvazione del campione e il ricevimento dell’acconto del {deposit}%. I tempi possono variare.',
    termsTitle: 'Condizioni commerciali e consegna globale', paymentTitle: 'Pagamento', paymentBody: 'I campioni richiedono pagamento anticipato del {samplePayment}%. Gli ordini in serie richiedono un acconto T/T del {deposit}%, con saldo prima della spedizione.', samplesToolingTitle: 'Campioni e attrezzature', creditBody: 'Il campione disponibile da {readyPrice} e il campione personalizzato da {customMin}–{customMax} sono interamente accreditati sull’ordine dello stesso modello al raggiungimento del MOQ. Logo da {logoFee}, spedizione e imposte sono esclusi.', toolingBody: 'Stampi e attrezzature pagati dal cliente appartengono al cliente. Nuovi attrezzi dovuti a modifiche vengono quotati separatamente.', deliveryTitle: 'Consegna', deliveryBody: 'Spediamo in tutto il mondo con DHL o con lo spedizioniere indicato dal cliente. Trasporto, dazi e imposte sono quotati separatamente.', quoteTitle: 'Vuoi parlarci del tuo progetto eyewear?', quoteBody: 'Invia materiale preferito, disegni o immagini di riferimento e requisiti di personalizzazione. Indica lo SKU per modificare un modello Kssmi.', reply: 'Rispondiamo normalmente entro un giorno lavorativo.',
  },
  es: {
    eyebrow: 'Guía para proyectos de marca privada', title: 'De la muestra a la producción', intro: 'Empiece con un modelo Kssmi existente o desarrolle unas gafas a partir de su propia idea. Consulte las opciones, el proceso de aprobación y lo necesario para comenzar.',
    routesTitle: 'Dos formas de empezar', readyTitle: 'Muestra en stock', readyBody: 'Se entrega con materiales, colores, lentes y especificaciones originales. Puede añadirse un logotipo estándar por {logoFee} por modelo; no se puede modificar ningún otro detalle.', customTitle: 'Desarrollo totalmente personalizado', customBody: 'Modifique un modelo existente o empiece con un boceto, fotografía, concepto generado por IA, muestra física o plano técnico completo.',
    optionsTitle: '¿Qué se puede personalizar?', optionsBody: 'Materiales, colores y medidas de la montura; materiales, tintes, tratamientos y funciones de las lentes; método y ubicación del logotipo; bisagras, herrajes, plaquetas, terminales, estructura, moldes y utillaje.', packaging: 'Nos especializamos en fabricar gafas y no fabricamos embalajes de venta al público.',
    processTitle: 'Cómo funciona el desarrollo', processSteps: ['Envíe su idea', 'Evaluación técnica y presupuesto', 'Render 2D y confirmación', 'Muestra física', 'Aprobación de muestra', 'Producción y control de calidad', 'Revisión y aprobación previa al envío', 'Entrega puerta a puerta'], processNote: 'Se incluyen hasta {revisions} rondas de revisión del render 2D. Los cambios solicitados después de terminar la muestra física pueden generar costes adicionales.',
    moqTimingTitle: 'MOQ y plazos estimados', standardMoq: 'La mayoría de materiales: {standardMoq} PCS por modelo', colorSplit: 'Hasta {colors} colores, mínimo {perColor} PCS por color', tr90Moq: 'TR90: {tr90Moq} PCS por modelo', leadTimesTitle: 'Plazos estimados', readyLabel: 'Muestra en stock', readyLogoLabel: 'Muestra en stock con logo', renderingLabel: 'Render 2D', customSampleLabel: 'Muestra totalmente personalizada', bulkLabel: 'Producción en serie', workingDays: 'días laborables', timingNote: 'El plazo de la muestra personalizada comienza tras aprobar el render 2D. La producción comienza tras aprobar la muestra y recibir el depósito del {deposit}%. Los plazos pueden variar.',
    termsTitle: 'Condiciones comerciales y entrega mundial', paymentTitle: 'Pago', paymentBody: 'Las muestras requieren un pago anticipado del {samplePayment}%. Los pedidos en serie requieren un depósito T/T del {deposit}% y el saldo antes del envío.', samplesToolingTitle: 'Muestras y utillaje', creditBody: 'Las muestras de {readyPrice} y {customMin}–{customMax} se acreditan íntegramente al pedido del mismo modelo cuando se alcanza el MOQ. El logo de {logoFee}, el transporte y los impuestos no se acreditan.', toolingBody: 'Los moldes y utillajes pagados por el cliente pertenecen al cliente. Los cambios que necesiten nuevas herramientas se cotizan por separado.', deliveryTitle: 'Entrega', deliveryBody: 'Enviamos a todo el mundo por DHL o con el transitario designado por el cliente. Flete, aranceles e impuestos se cotizan por separado.', quoteTitle: '¿Listo para hablar de su proyecto de gafas?', quoteBody: 'Envíe el material preferido, diseños o imágenes de referencia y requisitos. Incluya el SKU si desea modificar un modelo Kssmi.', reply: 'Normalmente respondemos en un día laborable.',
  },
  fr: {
    eyebrow: 'Guide du projet de marque privée', title: 'De l’échantillon à la production', intro: 'Partez d’un modèle Kssmi existant ou développez des lunettes depuis votre propre idée. Découvrez les options, les validations et les informations nécessaires pour commencer.',
    routesTitle: 'Deux façons de commencer', readyTitle: 'Échantillon en stock', readyBody: 'Fourni dans ses matériaux, couleurs, verres et spécifications d’origine. Un logo standard peut être ajouté pour {logoFee} par modèle ; aucun autre détail ne peut être modifié.', customTitle: 'Développement entièrement personnalisé', customBody: 'Modifiez un modèle existant ou partez d’un croquis, d’une photo, d’un concept IA, d’un échantillon physique ou d’un plan technique complet.',
    optionsTitle: 'Que peut-on personnaliser ?', optionsBody: 'Matériaux, couleurs et dimensions de la monture ; matériaux, teintes, traitements et fonctions des verres ; méthode et emplacement du logo ; charnières, pièces métalliques, plaquettes, embouts, structure, moules et outillage.', packaging: 'Nous sommes spécialisés dans la fabrication de lunettes et ne fabriquons pas d’emballages de vente au détail.',
    processTitle: 'Déroulement du développement', processSteps: ['Envoyez votre idée', 'Étude technique et devis', 'Rendu 2D et validation', 'Échantillon physique', 'Validation de l’échantillon', 'Production et contrôle qualité', 'Vérification et validation avant expédition', 'Livraison porte à porte'], processNote: 'Jusqu’à {revisions} séries de révisions du rendu 2D sont incluses. Les modifications après réalisation de l’échantillon peuvent entraîner des frais supplémentaires.',
    moqTimingTitle: 'MOQ et délais indicatifs', standardMoq: 'La plupart des matériaux : {standardMoq} PCS par modèle', colorSplit: 'Jusqu’à {colors} couleurs, minimum {perColor} PCS par couleur', tr90Moq: 'TR90 : {tr90Moq} PCS par modèle', leadTimesTitle: 'Délais indicatifs', readyLabel: 'Échantillon en stock', readyLogoLabel: 'Échantillon en stock avec logo', renderingLabel: 'Rendu 2D', customSampleLabel: 'Échantillon entièrement personnalisé', bulkLabel: 'Production en série', workingDays: 'jours ouvrés', timingNote: 'Le délai de l’échantillon personnalisé commence après validation du rendu 2D. La production commence après validation de l’échantillon et réception de l’acompte de {deposit} %. Les délais peuvent varier.',
    termsTitle: 'Conditions commerciales et livraison mondiale', paymentTitle: 'Paiement', paymentBody: 'Les échantillons sont payables à {samplePayment} % à l’avance. La production exige un acompte T/T de {deposit} %, le solde étant payé avant expédition.', samplesToolingTitle: 'Échantillons et outillage', creditBody: 'Les frais d’échantillon de {readyPrice} et {customMin}–{customMax} sont intégralement crédités sur la commande du même modèle lorsque le MOQ est atteint. Logo de {logoFee}, transport et taxes sont exclus.', toolingBody: 'Les moules et outillages payés par le client lui appartiennent. Toute modification nécessitant un nouvel outillage est devisée séparément.', deliveryTitle: 'Livraison', deliveryBody: 'Nous expédions dans le monde entier par DHL ou via votre transitaire désigné. Fret, droits et taxes sont devisés séparément.', quoteTitle: 'Prêt à parler de votre projet de lunettes ?', quoteBody: 'Envoyez le matériau souhaité, vos dessins ou images de référence et vos exigences. Indiquez le SKU pour modifier un modèle Kssmi.', reply: 'Nous répondons normalement sous un jour ouvré.',
  },
  de: {
    eyebrow: 'Leitfaden für Private-Label-Projekte', title: 'Vom Muster zur Produktion', intro: 'Starten Sie mit einem bestehenden Kssmi-Modell oder entwickeln Sie eine Brille aus Ihrer eigenen Idee. Hier sehen Sie Optionen, Freigaben und benötigte Angaben.',
    routesTitle: 'Zwei Wege zum Start', readyTitle: 'Lagerndes Muster', readyBody: 'Lieferung mit Originalmaterialien, -farben, -gläsern und -spezifikationen. Ein Standardlogo kann für {logoFee} je Modell ergänzt werden; weitere Änderungen sind nicht möglich.', customTitle: 'Vollständig individuelle Entwicklung', customBody: 'Ändern Sie ein bestehendes Modell oder starten Sie mit Skizze, Foto, KI-Konzept, physischem Muster oder vollständiger technischer Zeichnung.',
    optionsTitle: 'Was kann angepasst werden?', optionsBody: 'Fassungsmaterialien, Farben und Maße; Glasmaterialien, Tönungen, Beschichtungen und Funktionen; Logoverfahren und -position; Scharniere, Metallteile, Nasenpads, Bügelenden, Konstruktion, Formen und Werkzeuge.', packaging: 'Wir sind auf Brillenfertigung spezialisiert und stellen keine Verkaufsverpackungen her.',
    processTitle: 'Ablauf der Entwicklung', processSteps: ['Idee senden', 'Technische Prüfung und Angebot', '2D-Rendering und Freigabe', 'Physisches Muster', 'Musterfreigabe', 'Produktion und Qualitätskontrolle', 'Prüfung und Freigabe vor Versand', 'Lieferung bis zur Haustür'], processNote: 'Bis zu {revisions} Überarbeitungsrunden des 2D-Renderings sind enthalten. Änderungen nach Fertigstellung des Musters können zusätzliche Entwicklungs- oder Werkzeugkosten verursachen.',
    moqTimingTitle: 'MOQ und Richtzeiten', standardMoq: 'Die meisten Materialien: {standardMoq} PCS je Modell', colorSplit: 'Bis zu {colors} Farben, mindestens {perColor} PCS je Farbe', tr90Moq: 'TR90: {tr90Moq} PCS je Modell', leadTimesTitle: 'Richtzeiten', readyLabel: 'Lagerndes Muster', readyLogoLabel: 'Lagerndes Muster mit Logo', renderingLabel: '2D-Rendering', customSampleLabel: 'Vollständig individuelles Muster', bulkLabel: 'Serienproduktion', workingDays: 'Arbeitstage', timingNote: 'Die Musterzeit beginnt nach Freigabe des 2D-Renderings. Die Serienzeit beginnt nach Musterfreigabe und Eingang der {deposit}% Anzahlung. Zeiten können variieren.',
    termsTitle: 'Geschäftsbedingungen und weltweite Lieferung', paymentTitle: 'Zahlung', paymentBody: 'Muster sind zu {samplePayment}% im Voraus zahlbar. Serienaufträge erfordern {deposit}% T/T-Anzahlung; der Restbetrag ist vor Versand fällig.', samplesToolingTitle: 'Muster und Werkzeuge', creditBody: 'Die Mustergebühren von {readyPrice} und {customMin}–{customMax} werden bei Erreichen der MOQ vollständig auf den Serienauftrag desselben Modells angerechnet. Logo von {logoFee}, Versand und Steuern sind ausgeschlossen.', toolingBody: 'Vom Kunden bezahlte Formen und Werkzeuge gehören dem Kunden. Änderungen mit neuem Werkzeug werden separat angeboten.', deliveryTitle: 'Lieferung', deliveryBody: 'Wir versenden weltweit per DHL oder über Ihren benannten Spediteur. Fracht, Zölle und Steuern werden separat angeboten.', quoteTitle: 'Bereit für Ihr Brillenprojekt?', quoteBody: 'Senden Sie gewünschtes Material, Entwürfe oder Referenzbilder und Anforderungen. Geben Sie bei Änderungen eines Kssmi-Modells die SKU an.', reply: 'Wir antworten normalerweise innerhalb eines Arbeitstages.',
  },
  pt: {
    eyebrow: 'Guia de projeto de marca própria', title: 'Da amostra à produção', intro: 'Comece com um modelo Kssmi existente ou desenvolva óculos a partir da sua ideia. Veja as opções, aprovações e informações necessárias para começar.',
    routesTitle: 'Duas formas de começar', readyTitle: 'Amostra em stock', readyBody: 'Fornecida com materiais, cores, lentes e especificações originais. Pode ser acrescentado um logótipo padrão por {logoFee} por modelo; nenhum outro detalhe pode ser alterado.', customTitle: 'Desenvolvimento totalmente personalizado', customBody: 'Modifique um modelo existente ou comece com esboço, fotografia, conceito de IA, amostra física ou desenho técnico completo.',
    optionsTitle: 'O que pode ser personalizado?', optionsBody: 'Materiais, cores e dimensões da armação; materiais, tonalidades, revestimentos e funções das lentes; método e posição do logótipo; dobradiças, ferragens, plaquetas, ponteiras, estrutura, moldes e ferramentas.', packaging: 'Somos especializados no fabrico de óculos e não fabricamos embalagens de retalho.',
    processTitle: 'Como funciona o desenvolvimento', processSteps: ['Envie a sua ideia', 'Avaliação técnica e cotação', 'Renderização 2D e aprovação', 'Amostra física', 'Aprovação da amostra', 'Produção e controlo de qualidade', 'Revisão e aprovação antes do envio', 'Entrega porta a porta'], processNote: 'Estão incluídas até {revisions} rondas de revisão da renderização 2D. Alterações após a amostra física podem gerar custos adicionais.',
    moqTimingTitle: 'MOQ e prazos indicativos', standardMoq: 'Maioria dos materiais: {standardMoq} PCS por modelo', colorSplit: 'Até {colors} cores, mínimo {perColor} PCS por cor', tr90Moq: 'TR90: {tr90Moq} PCS por modelo', leadTimesTitle: 'Prazos indicativos', readyLabel: 'Amostra em stock', readyLogoLabel: 'Amostra em stock com logótipo', renderingLabel: 'Renderização 2D', customSampleLabel: 'Amostra totalmente personalizada', bulkLabel: 'Produção em série', workingDays: 'dias úteis', timingNote: 'O prazo da amostra personalizada começa após aprovação do 2D. A produção começa após aprovação da amostra e receção do depósito de {deposit}%. Os prazos podem variar.',
    termsTitle: 'Condições comerciais e entrega mundial', paymentTitle: 'Pagamento', paymentBody: 'As amostras exigem {samplePayment}% de pagamento antecipado. A produção exige depósito T/T de {deposit}%, com saldo antes do envio.', samplesToolingTitle: 'Amostras e ferramentas', creditBody: 'As taxas de amostra de {readyPrice} e {customMin}–{customMax} são integralmente creditadas na encomenda do mesmo modelo quando o MOQ é atingido. Logótipo de {logoFee}, transporte e impostos ficam excluídos.', toolingBody: 'Moldes e ferramentas pagos pelo cliente pertencem ao cliente. Alterações que exijam novas ferramentas são cotadas separadamente.', deliveryTitle: 'Entrega', deliveryBody: 'Enviamos para todo o mundo por DHL ou através do transitário indicado pelo cliente. Frete, direitos e impostos são cotados separadamente.', quoteTitle: 'Pronto para falar sobre o seu projeto?', quoteBody: 'Envie o material preferido, desenhos ou imagens de referência e requisitos. Inclua o SKU ao modificar um modelo Kssmi.', reply: 'Normalmente respondemos num dia útil.',
  },
  ar: {
    eyebrow: 'دليل مشروع العلامة الخاصة', title: 'من العينة إلى الإنتاج', intro: 'ابدأ بموديل Kssmi قائم أو طوّر نظارة من فكرتك. تعرّف على خيارات التخصيص ومراحل الاعتماد والمعلومات اللازمة للبدء.',
    routesTitle: 'طريقتان للبدء', readyTitle: 'عينة جاهزة من المخزون', readyBody: 'تُقدَّم بخاماتها وألوانها وعدساتها ومواصفاتها الأصلية. يمكن إضافة شعار قياسي مقابل {logoFee} لكل موديل، ولا يمكن تغيير أي تفاصيل أخرى.', customTitle: 'تطوير مخصص بالكامل', customBody: 'عدّل موديلًا قائمًا أو ابدأ من رسم أو صورة أو فكرة مولّدة بالذكاء الاصطناعي أو عينة فعلية أو مخطط تقني كامل.',
    optionsTitle: 'ما الذي يمكن تخصيصه؟', optionsBody: 'خامات الإطار وألوانه ومقاساته؛ خامات العدسات وألوانها وطلاءاتها ووظائفها؛ طريقة الشعار وموضعه؛ المفصلات والقطع المعدنية ووسادات الأنف وأطراف الأذرع والتفاصيل الهيكلية والقوالب والأدوات.', packaging: 'نحن متخصصون في تصنيع النظارات ولا نصنّع عبوات البيع بالتجزئة.',
    processTitle: 'كيف يتم التطوير المخصص؟', processSteps: ['أرسل فكرتك', 'مراجعة هندسية وعرض سعر', 'تصميم ثنائي الأبعاد واعتماد', 'عينة فعلية', 'اعتماد العينة', 'الإنتاج ومراقبة الجودة', 'المراجعة والاعتماد قبل الشحن', 'توصيل من الباب إلى الباب'], processNote: 'يشمل السعر حتى {revisions} جولات تعديل للتصميم ثنائي الأبعاد. قد تتطلب التغييرات بعد اكتمال العينة تكاليف تطوير أو قوالب إضافية.',
    moqTimingTitle: 'الحد الأدنى والمهل التقديرية', standardMoq: 'معظم الخامات: {standardMoq} قطعة لكل موديل', colorSplit: 'حتى {colors} ألوان، بحد أدنى {perColor} قطعة لكل لون', tr90Moq: 'TR90: ‏{tr90Moq} قطعة لكل موديل', leadTimesTitle: 'المهل التقديرية', readyLabel: 'عينة جاهزة', readyLogoLabel: 'عينة جاهزة مع شعار', renderingLabel: 'تصميم ثنائي الأبعاد', customSampleLabel: 'عينة مخصصة بالكامل', bulkLabel: 'إنتاج كمي', workingDays: 'أيام عمل', timingNote: 'تبدأ مهلة العينة المخصصة بعد اعتماد التصميم ثنائي الأبعاد. وتبدأ مهلة الإنتاج بعد اعتماد العينة واستلام دفعة {deposit}%. قد تختلف المدة حسب الخامات والتعقيد والطاقة الإنتاجية.',
    termsTitle: 'الشروط التجارية والتوصيل العالمي', paymentTitle: 'الدفع', paymentBody: 'تتطلب العينات دفع {samplePayment}% مقدمًا. وتتطلب طلبات الإنتاج دفعة T/T بنسبة {deposit}%، ويُدفع الرصيد قبل الشحن.', samplesToolingTitle: 'العينات والقوالب', creditBody: 'تُخصم بالكامل رسوم العينة {readyPrice} والعينة المخصصة {customMin}–{customMax} من طلب الإنتاج لنفس الموديل عند بلوغ الحد الأدنى. ولا تُخصم رسوم الشعار {logoFee} أو الشحن أو الضرائب.', toolingBody: 'القوالب والأدوات التي يدفع ثمنها العميل ملك للعميل. ويُعاد التسعير عند الحاجة إلى أدوات جديدة بسبب تغيير التصميم.', deliveryTitle: 'التوصيل', deliveryBody: 'نشحن عالميًا عبر DHL أو نتعامل مع وكيل الشحن الذي يحدده العميل. تُسعّر أجور الشحن والرسوم والضرائب بشكل منفصل.', quoteTitle: 'هل أنت مستعد لمناقشة مشروع النظارات؟', quoteBody: 'أرسل الخامة المفضلة والتصميم أو الصور المرجعية ومتطلبات التخصيص. أرفق SKU عند تعديل موديل Kssmi قائم.', reply: 'نرد عادة خلال يوم عمل واحد.',
  },
  ru: {
    eyebrow: 'Руководство по private-label проекту', title: 'От образца до производства', intro: 'Начните с готовой модели Kssmi или разработайте очки по собственной идее. Здесь указаны варианты, этапы согласования и данные для старта.',
    routesTitle: 'Два способа начать', readyTitle: 'Образец со склада', readyBody: 'Поставляется в исходных материалах, цветах, линзах и спецификации. Стандартный логотип можно добавить за {logoFee} на модель; другие изменения невозможны.', customTitle: 'Полностью индивидуальная разработка', customBody: 'Измените готовую модель или начните с эскиза, фотографии, AI-концепта, физического образца либо полного технического чертежа.',
    optionsTitle: 'Что можно изменить?', optionsBody: 'Материалы, цвета и размеры оправы; материалы, оттенки, покрытия и функции линз; способ и место нанесения логотипа; шарниры, фурнитура, носоупоры, заушники, конструкция, формы и оснастка.', packaging: 'Мы специализируемся на производстве очков и не изготавливаем розничную упаковку.',
    processTitle: 'Как проходит разработка', processSteps: ['Отправка идеи', 'Инженерная оценка и расчёт', '2D-визуализация и согласование', 'Физический образец', 'Утверждение образца', 'Производство и контроль качества', 'Проверка и согласование перед отгрузкой', 'Доставка до двери'], processNote: 'Включено до {revisions} раундов правок 2D-визуализации. Изменения после изготовления образца могут потребовать дополнительной оплаты.',
    moqTimingTitle: 'MOQ и ориентировочные сроки', standardMoq: 'Большинство материалов: {standardMoq} PCS на модель', colorSplit: 'До {colors} цветов, минимум {perColor} PCS на цвет', tr90Moq: 'TR90: {tr90Moq} PCS на модель', leadTimesTitle: 'Ориентировочные сроки', readyLabel: 'Образец со склада', readyLogoLabel: 'Образец со склада с логотипом', renderingLabel: '2D-визуализация', customSampleLabel: 'Полностью индивидуальный образец', bulkLabel: 'Серийное производство', workingDays: 'рабочих дней', timingNote: 'Срок образца начинается после утверждения 2D-визуализации. Срок производства начинается после утверждения образца и получения депозита {deposit}%. Фактические сроки могут меняться.',
    termsTitle: 'Коммерческие условия и доставка по миру', paymentTitle: 'Оплата', paymentBody: 'Образцы оплачиваются на {samplePayment}% заранее. Для серийного заказа требуется депозит T/T {deposit}%, остаток — до отгрузки.', samplesToolingTitle: 'Образцы и оснастка', creditBody: 'Стоимость образцов {readyPrice} и {customMin}–{customMax} полностью засчитывается в заказ той же модели при достижении MOQ. Логотип {logoFee}, доставка и налоги не засчитываются.', toolingBody: 'Оплаченные клиентом формы и оснастка принадлежат клиенту. Новая оснастка при изменении дизайна рассчитывается отдельно.', deliveryTitle: 'Доставка', deliveryBody: 'Отправляем по всему миру через DHL или перевозчика клиента. Фрахт, пошлины и налоги рассчитываются отдельно.', quoteTitle: 'Готовы обсудить проект очков?', quoteBody: 'Пришлите материал, дизайн или референсы и требования. При изменении модели Kssmi укажите SKU.', reply: 'Обычно мы отвечаем в течение одного рабочего дня.',
  },
  ja: {
    eyebrow: 'プライベートブランド・プロジェクトガイド', title: 'サンプルから量産まで', intro: '既存のKssmiモデルから始めることも、お客様のアイデアから眼鏡を開発することもできます。カスタマイズ範囲、承認工程、開始に必要な情報をご確認ください。',
    routesTitle: '2つの開始方法', readyTitle: '在庫サンプル', readyBody: '既存の素材、色、レンズ、仕様のまま提供します。モデルごとに{logoFee}で標準ロゴを追加できますが、その他の変更はできません。', customTitle: 'フルカスタム開発', customBody: '既存モデルの変更、またはスケッチ、写真、AI生成コンセプト、現物サンプル、完全な技術図面から開発できます。',
    optionsTitle: 'カスタマイズできる内容', optionsBody: 'フレーム素材、色、寸法、レンズ素材、カラー、コーティング、機能、ロゴ方法と位置、ヒンジ、金属部品、ノーズパッド、テンプルチップ、構造、金型、治具。', packaging: '当社は眼鏡製造を専門としており、小売用パッケージは製造していません。',
    processTitle: 'カスタム開発の流れ', processSteps: ['アイデアを送付', '技術評価と見積り', '2Dレンダリングと承認', '現物サンプル', 'サンプル承認', '量産と品質管理', '出荷前確認と承認', 'ドア・ツー・ドア配送'], processNote: '2Dレンダリングは最大{revisions}回の修正を含みます。現物サンプル完成後の変更には追加の開発費または金型費が発生する場合があります。',
    moqTimingTitle: 'MOQと標準納期', standardMoq: '大多数の素材：1モデル{standardMoq} PCS', colorSplit: '最大{colors}色、1色最低{perColor} PCS', tr90Moq: 'TR90：1モデル{tr90Moq} PCS', leadTimesTitle: '標準納期', readyLabel: '在庫サンプル', readyLogoLabel: 'ロゴ付き在庫サンプル', renderingLabel: '2Dレンダリング', customSampleLabel: 'フルカスタムサンプル', bulkLabel: '量産', workingDays: '営業日', timingNote: 'カスタムサンプルの納期は2D承認後に開始します。量産納期はサンプル承認と{deposit}%の前金受領後に開始します。素材や複雑さ等により変動します。',
    termsTitle: '取引条件と世界配送', paymentTitle: '支払い', paymentBody: 'サンプルは{samplePayment}%前払いです。量産はT/Tで{deposit}%の前金、残金は出荷前にお支払いいただきます。', samplesToolingTitle: 'サンプルと金型', creditBody: '{readyPrice}および{customMin}–{customMax}のサンプル代は、同一モデルでMOQを満たす量産注文から全額控除されます。{logoFee}のロゴ代、送料、税金は対象外です。', toolingBody: 'お客様が支払った金型と治具はお客様の所有です。新しい金型が必要な設計変更は別途見積ります。', deliveryTitle: '配送', deliveryBody: 'DHLまたはお客様指定のフォワーダーで世界中へ発送します。送料、関税、税金は別途見積ります。', quoteTitle: '眼鏡プロジェクトについて相談しませんか？', quoteBody: '希望素材、デザインまたは参考画像、カスタマイズ要件をお送りください。既存Kssmiモデルを変更する場合はSKUもご記載ください。', reply: '通常1営業日以内に返信します。',
  },
  tr: {
    eyebrow: 'Özel marka proje rehberi', title: 'Numuneden Üretime', intro: 'Mevcut bir Kssmi modeliyle başlayın veya kendi fikrinizden gözlük geliştirin. Özelleştirme, onay süreci ve başlangıç için gerekenleri görün.',
    routesTitle: 'Başlamanın iki yolu', readyTitle: 'Stok numunesi', readyBody: 'Orijinal malzeme, renk, cam ve özelliklerle sunulur. Model başına {logoFee} karşılığında standart logo eklenebilir; başka hiçbir ayrıntı değiştirilemez.', customTitle: 'Tam özel geliştirme', customBody: 'Mevcut modeli değiştirin veya eskiz, fotoğraf, yapay zekâ konsepti, fiziksel numune ya da tam teknik çizimden başlayın.',
    optionsTitle: 'Neler özelleştirilebilir?', optionsBody: 'Çerçeve malzemesi, renk ve ölçüler; cam malzemesi, rengi, kaplaması ve işlevi; logo yöntemi ve konumu; menteşe, metal parçalar, burun pedi, sap ucu, yapı, kalıp ve takımlar.', packaging: 'Gözlük üretiminde uzmanız; perakende ambalajı üretmiyoruz.',
    processTitle: 'Özel geliştirme süreci', processSteps: ['Fikrinizi gönderin', 'Mühendislik incelemesi ve teklif', '2D görsel ve onay', 'Fiziksel numune', 'Numune onayı', 'Üretim ve kalite kontrol', 'Sevkiyat öncesi inceleme ve onay', 'Kapıdan kapıya teslimat'], processNote: 'En fazla {revisions} tur 2D revizyon dahildir. Fiziksel numune tamamlandıktan sonraki değişiklikler ek geliştirme veya kalıp ücreti gerektirebilir.',
    moqTimingTitle: 'MOQ ve tahmini süreler', standardMoq: 'Çoğu malzeme: model başına {standardMoq} PCS', colorSplit: 'En fazla {colors} renk, renk başına en az {perColor} PCS', tr90Moq: 'TR90: model başına {tr90Moq} PCS', leadTimesTitle: 'Tahmini süreler', readyLabel: 'Stok numunesi', readyLogoLabel: 'Logolu stok numunesi', renderingLabel: '2D görsel', customSampleLabel: 'Tam özel numune', bulkLabel: 'Seri üretim', workingDays: 'iş günü', timingNote: 'Özel numune süresi 2D onayından sonra başlar. Seri üretim, numune onayı ve %{deposit} depozito alındıktan sonra başlar. Süreler değişebilir.',
    termsTitle: 'Ticari şartlar ve dünya çapında teslimat', paymentTitle: 'Ödeme', paymentBody: 'Numuneler %{samplePayment} peşin ödenir. Seri siparişlerde %{deposit} T/T depozito, kalan tutar sevkiyattan önce ödenir.', samplesToolingTitle: 'Numune ve kalıplar', creditBody: '{readyPrice} ve {customMin}–{customMax} numune ücretleri, aynı model MOQ’ya ulaştığında seri siparişten tamamen düşülür. {logoFee} logo ücreti, nakliye ve vergiler düşülmez.', toolingBody: 'Müşterinin ödediği kalıp ve takımlar müşteriye aittir. Yeni takım gerektiren tasarım değişiklikleri ayrıca fiyatlandırılır.', deliveryTitle: 'Teslimat', deliveryBody: 'DHL veya müşterinin belirlediği nakliyeciyle dünya çapında gönderim yaparız. Navlun, gümrük ve vergiler ayrıca fiyatlandırılır.', quoteTitle: 'Gözlük projenizi görüşmeye hazır mısınız?', quoteBody: 'Tercih ettiğiniz malzemeyi, tasarım veya referans görsellerini ve taleplerinizi gönderin. Mevcut Kssmi modelini değiştirirken SKU’yu ekleyin.', reply: 'Normalde bir iş günü içinde yanıt veririz.',
  },
  ko: {
    eyebrow: '프라이빗 라벨 프로젝트 안내', title: '샘플에서 생산까지', intro: '기존 Kssmi 모델로 시작하거나 아이디어에서 안경을 개발할 수 있습니다. 맞춤 범위, 승인 과정과 시작에 필요한 정보를 확인하세요.',
    routesTitle: '두 가지 시작 방법', readyTitle: '재고 샘플', readyBody: '기존 소재, 색상, 렌즈와 사양 그대로 제공합니다. 모델당 {logoFee}에 표준 로고를 추가할 수 있으며 그 외 변경은 불가능합니다.', customTitle: '완전 맞춤 개발', customBody: '기존 모델을 수정하거나 스케치, 사진, AI 콘셉트, 실물 샘플 또는 전체 기술 도면에서 시작할 수 있습니다.',
    optionsTitle: '맞춤 가능한 항목', optionsBody: '프레임 소재, 색상과 치수; 렌즈 소재, 색상, 코팅과 기능; 로고 방식과 위치; 힌지, 금속 부품, 코받침, 팁, 구조, 금형과 툴링.', packaging: '당사는 안경 제조 전문 업체이며 소매 포장은 생산하지 않습니다.',
    processTitle: '맞춤 개발 절차', processSteps: ['아이디어 전달', '기술 검토와 견적', '2D 렌더링과 승인', '실물 샘플', '샘플 승인', '대량 생산과 품질 관리', '출하 전 검토와 승인', '도어 투 도어 배송'], processNote: '2D 렌더링 수정은 최대 {revisions}회 포함됩니다. 실물 샘플 완성 후 변경에는 추가 개발비나 금형비가 발생할 수 있습니다.',
    moqTimingTitle: 'MOQ와 예상 기간', standardMoq: '대부분 소재: 모델당 {standardMoq} PCS', colorSplit: '최대 {colors}색, 색상당 최소 {perColor} PCS', tr90Moq: 'TR90: 모델당 {tr90Moq} PCS', leadTimesTitle: '예상 기간', readyLabel: '재고 샘플', readyLogoLabel: '로고 추가 재고 샘플', renderingLabel: '2D 렌더링', customSampleLabel: '완전 맞춤 샘플', bulkLabel: '대량 생산', workingDays: '영업일', timingNote: '맞춤 샘플 기간은 2D 승인 후 시작됩니다. 대량 생산은 샘플 승인과 {deposit}% 계약금 수령 후 시작됩니다. 실제 기간은 달라질 수 있습니다.',
    termsTitle: '거래 조건과 전 세계 배송', paymentTitle: '결제', paymentBody: '샘플은 {samplePayment}% 선결제입니다. 대량 주문은 T/T {deposit}% 계약금, 잔금은 출하 전에 지급합니다.', samplesToolingTitle: '샘플과 금형', creditBody: '{readyPrice} 및 {customMin}–{customMax} 샘플비는 동일 모델이 MOQ를 충족하면 대량 주문에서 전액 공제됩니다. {logoFee} 로고비, 배송비와 세금은 제외됩니다.', toolingBody: '고객이 비용을 지불한 금형과 툴링은 고객 소유입니다. 새 금형이 필요한 설계 변경은 별도 견적합니다.', deliveryTitle: '배송', deliveryBody: 'DHL 또는 고객 지정 포워더로 전 세계 배송합니다. 운임, 관세와 세금은 별도 견적합니다.', quoteTitle: '안경 프로젝트를 상담하시겠습니까?', quoteBody: '선호 소재, 디자인 또는 참고 이미지와 맞춤 요구사항을 보내 주세요. 기존 Kssmi 모델 수정 시 SKU를 포함하세요.', reply: '보통 영업일 기준 하루 안에 답변합니다.',
  },
  hi: {
    eyebrow: 'प्राइवेट-लेबल प्रोजेक्ट गाइड', title: 'सैंपल से उत्पादन तक', intro: 'मौजूदा Kssmi मॉडल से शुरू करें या अपने विचार से आईवियर विकसित करें। कस्टम विकल्प, अनुमोदन प्रक्रिया और शुरुआत के लिए आवश्यक जानकारी देखें।',
    routesTitle: 'शुरू करने के दो तरीके', readyTitle: 'रेडी-स्टॉक सैंपल', readyBody: 'मूल सामग्री, रंग, लेंस और विनिर्देशों में दिया जाता है। प्रति मॉडल {logoFee} में मानक लोगो जोड़ा जा सकता है; अन्य बदलाव संभव नहीं हैं।', customTitle: 'पूरी तरह कस्टम विकास', customBody: 'मौजूदा मॉडल बदलें या स्केच, फोटो, AI कॉन्सेप्ट, भौतिक सैंपल या पूर्ण तकनीकी ड्रॉइंग से शुरू करें।',
    optionsTitle: 'क्या कस्टम किया जा सकता है?', optionsBody: 'फ्रेम सामग्री, रंग और माप; लेंस सामग्री, टिंट, कोटिंग और कार्य; लोगो विधि और स्थान; हिंज, हार्डवेयर, नोज पैड, टेंपल टिप, संरचना, मोल्ड और टूलिंग।', packaging: 'हम आईवियर निर्माण में विशेषज्ञ हैं और रिटेल पैकेजिंग का निर्माण नहीं करते।',
    processTitle: 'कस्टम विकास कैसे होता है', processSteps: ['अपना विचार भेजें', 'इंजीनियरिंग समीक्षा और कोटेशन', '2D रेंडरिंग और पुष्टि', 'भौतिक सैंपल', 'सैंपल अनुमोदन', 'उत्पादन और गुणवत्ता नियंत्रण', 'शिपमेंट-पूर्व समीक्षा और अनुमोदन', 'डोर-टू-डोर डिलीवरी'], processNote: '2D रेंडरिंग के अधिकतम {revisions} संशोधन दौर शामिल हैं। भौतिक सैंपल बनने के बाद बदलाव पर अतिरिक्त विकास या टूलिंग शुल्क लग सकता है।',
    moqTimingTitle: 'MOQ और सामान्य समय', standardMoq: 'अधिकांश सामग्री: प्रति मॉडल {standardMoq} PCS', colorSplit: 'अधिकतम {colors} रंग, प्रति रंग न्यूनतम {perColor} PCS', tr90Moq: 'TR90: प्रति मॉडल {tr90Moq} PCS', leadTimesTitle: 'सामान्य समय', readyLabel: 'रेडी-स्टॉक सैंपल', readyLogoLabel: 'लोगो सहित स्टॉक सैंपल', renderingLabel: '2D रेंडरिंग', customSampleLabel: 'पूरी तरह कस्टम सैंपल', bulkLabel: 'बल्क उत्पादन', workingDays: 'कार्य दिवस', timingNote: 'कस्टम सैंपल का समय 2D अनुमोदन के बाद शुरू होता है। बल्क समय सैंपल अनुमोदन और {deposit}% जमा मिलने के बाद शुरू होता है। वास्तविक समय बदल सकता है।',
    termsTitle: 'व्यावसायिक शर्तें और वैश्विक डिलीवरी', paymentTitle: 'भुगतान', paymentBody: 'सैंपल के लिए {samplePayment}% अग्रिम भुगतान आवश्यक है। बल्क ऑर्डर के लिए {deposit}% T/T जमा और शेष भुगतान शिपमेंट से पहले आवश्यक है।', samplesToolingTitle: 'सैंपल और टूलिंग', creditBody: '{readyPrice} और {customMin}–{customMax} सैंपल शुल्क उसी मॉडल के MOQ वाले बल्क ऑर्डर में पूरा समायोजित होता है। {logoFee} लोगो शुल्क, शिपिंग और कर शामिल नहीं हैं।', toolingBody: 'ग्राहक द्वारा भुगतान किए गए मोल्ड और टूलिंग ग्राहक के स्वामित्व में रहते हैं। नए टूलिंग वाले बदलाव अलग से कोट किए जाते हैं।', deliveryTitle: 'डिलीवरी', deliveryBody: 'हम DHL या ग्राहक के नामित फ्रेट फॉरवर्डर से विश्वभर में भेजते हैं। मालभाड़ा, शुल्क और कर अलग कोट होते हैं।', quoteTitle: 'अपने आईवियर प्रोजेक्ट पर चर्चा के लिए तैयार हैं?', quoteBody: 'पसंदीदा सामग्री, डिज़ाइन या संदर्भ चित्र और कस्टम आवश्यकताएँ भेजें। मौजूदा Kssmi मॉडल बदलते समय SKU शामिल करें।', reply: 'हम सामान्यतः एक कार्य दिवस में उत्तर देते हैं।',
  },
  vi: {
    eyebrow: 'Hướng dẫn dự án nhãn riêng', title: 'Từ mẫu đến sản xuất', intro: 'Bắt đầu với mẫu Kssmi hiện có hoặc phát triển kính từ ý tưởng của bạn. Xem phạm vi tùy chỉnh, quy trình duyệt và thông tin cần để bắt đầu.',
    routesTitle: 'Hai cách để bắt đầu', readyTitle: 'Mẫu có sẵn', readyBody: 'Được cung cấp theo vật liệu, màu sắc, tròng kính và thông số nguyên bản. Có thể thêm logo tiêu chuẩn với phí {logoFee} cho mỗi mẫu mã; không thể thay đổi chi tiết khác.', customTitle: 'Phát triển hoàn toàn tùy chỉnh', customBody: 'Điều chỉnh mẫu hiện có hoặc bắt đầu từ bản phác thảo, ảnh, ý tưởng AI, mẫu vật lý hoặc bản vẽ kỹ thuật đầy đủ.',
    optionsTitle: 'Có thể tùy chỉnh gì?', optionsBody: 'Vật liệu, màu và kích thước gọng; vật liệu, màu, lớp phủ và chức năng tròng; phương pháp và vị trí logo; bản lề, chi tiết kim loại, đệm mũi, đầu càng, kết cấu, khuôn và dụng cụ.', packaging: 'Chúng tôi chuyên sản xuất kính và không sản xuất bao bì bán lẻ.',
    processTitle: 'Quy trình phát triển tùy chỉnh', processSteps: ['Gửi ý tưởng', 'Đánh giá kỹ thuật và báo giá', 'Phối cảnh 2D và xác nhận', 'Mẫu vật lý', 'Duyệt mẫu', 'Sản xuất và kiểm soát chất lượng', 'Kiểm tra và duyệt trước khi giao', 'Giao hàng tận nơi'], processNote: 'Bao gồm tối đa {revisions} vòng chỉnh sửa phối cảnh 2D. Thay đổi sau khi hoàn tất mẫu vật lý có thể phát sinh phí phát triển hoặc khuôn.',
    moqTimingTitle: 'MOQ và thời gian dự kiến', standardMoq: 'Hầu hết vật liệu: {standardMoq} PCS mỗi mẫu', colorSplit: 'Tối đa {colors} màu, tối thiểu {perColor} PCS mỗi màu', tr90Moq: 'TR90: {tr90Moq} PCS mỗi mẫu', leadTimesTitle: 'Thời gian dự kiến', readyLabel: 'Mẫu có sẵn', readyLogoLabel: 'Mẫu có sẵn kèm logo', renderingLabel: 'Phối cảnh 2D', customSampleLabel: 'Mẫu hoàn toàn tùy chỉnh', bulkLabel: 'Sản xuất hàng loạt', workingDays: 'ngày làm việc', timingNote: 'Thời gian làm mẫu tùy chỉnh bắt đầu sau khi duyệt 2D. Sản xuất bắt đầu sau khi duyệt mẫu và nhận cọc {deposit}%. Thời gian thực tế có thể thay đổi.',
    termsTitle: 'Điều khoản thương mại và giao hàng toàn cầu', paymentTitle: 'Thanh toán', paymentBody: 'Mẫu phải thanh toán trước {samplePayment}%. Đơn hàng số lượng lớn đặt cọc T/T {deposit}%, phần còn lại thanh toán trước khi giao.', samplesToolingTitle: 'Mẫu và khuôn', creditBody: 'Phí mẫu {readyPrice} và {customMin}–{customMax} được khấu trừ toàn bộ vào đơn hàng cùng mẫu đạt MOQ. Phí logo {logoFee}, vận chuyển và thuế không được khấu trừ.', toolingBody: 'Khuôn và dụng cụ do khách hàng thanh toán thuộc sở hữu khách hàng. Thay đổi cần dụng cụ mới được báo giá riêng.', deliveryTitle: 'Giao hàng', deliveryBody: 'Chúng tôi giao toàn cầu bằng DHL hoặc đơn vị vận chuyển do khách chỉ định. Cước, thuế quan và thuế được báo riêng.', quoteTitle: 'Sẵn sàng trao đổi về dự án kính?', quoteBody: 'Gửi vật liệu mong muốn, thiết kế hoặc ảnh tham khảo và yêu cầu tùy chỉnh. Kèm SKU khi sửa mẫu Kssmi hiện có.', reply: 'Chúng tôi thường phản hồi trong một ngày làm việc.',
  },
  jv: {
    eyebrow: 'Pandhuan proyek merek pribadi', title: 'Saka Sampel nganti Produksi', intro: 'Miwiti saka model Kssmi sing wis ana utawa gawe kacamata saka gagasan sampeyan. Deleng pilihan kustom, proses persetujuan lan informasi kanggo miwiti.',
    routesTitle: 'Rong cara kanggo miwiti', readyTitle: 'Sampel stok', readyBody: 'Disedhiyakake nganggo bahan, warna, lensa lan spesifikasi asli. Logo standar bisa ditambah kanthi biaya {logoFee} saben model; rincian liyane ora bisa diganti.', customTitle: 'Pangembangan kustom lengkap', customBody: 'Owahi model sing wis ana utawa miwiti saka sketsa, foto, konsep AI, sampel fisik utawa gambar teknis lengkap.',
    optionsTitle: 'Apa sing bisa dikustom?', optionsBody: 'Bahan, warna lan ukuran frame; bahan, warna, lapisan lan fungsi lensa; cara lan posisi logo; engsel, hardware, nose pad, temple tip, struktur, cetakan lan tooling.', packaging: 'Kita spesialis manufaktur kacamata lan ora nggawe kemasan retail.',
    processTitle: 'Proses pangembangan kustom', processSteps: ['Kirim gagasan', 'Tinjauan teknik lan penawaran', 'Rendering 2D lan konfirmasi', 'Sampel fisik', 'Persetujuan sampel', 'Produksi lan kontrol kualitas', 'Tinjauan lan persetujuan sadurunge dikirim', 'Kiriman nganti lawang'], processNote: 'Kalebu nganti {revisions} babak revisi rendering 2D. Owah-owahan sawise sampel rampung bisa mbutuhake biaya pangembangan utawa tooling tambahan.',
    moqTimingTitle: 'MOQ lan wektu perkiraan', standardMoq: 'Umume bahan: {standardMoq} PCS saben model', colorSplit: 'Nganti {colors} warna, minimal {perColor} PCS saben warna', tr90Moq: 'TR90: {tr90Moq} PCS saben model', leadTimesTitle: 'Wektu perkiraan', readyLabel: 'Sampel stok', readyLogoLabel: 'Sampel stok nganggo logo', renderingLabel: 'Rendering 2D', customSampleLabel: 'Sampel kustom lengkap', bulkLabel: 'Produksi massal', workingDays: 'dina kerja', timingNote: 'Wektu sampel kustom diwiwiti sawise 2D disetujoni. Produksi diwiwiti sawise sampel disetujoni lan deposit {deposit}% ditampa. Wektu nyata bisa beda.',
    termsTitle: 'Syarat dagang lan kiriman global', paymentTitle: 'Pembayaran', paymentBody: 'Sampel kudu dibayar {samplePayment}% ing ngarep. Pesanan massal mbutuhake deposit T/T {deposit}%, sisane sadurunge dikirim.', samplesToolingTitle: 'Sampel lan tooling', creditBody: 'Biaya sampel {readyPrice} lan {customMin}–{customMax} dikreditake kanthi lengkap kanggo pesanan model sing padha yen MOQ ketemu. Biaya logo {logoFee}, kiriman lan pajak ora kalebu.', toolingBody: 'Cetakan lan tooling sing dibayar pelanggan dadi duweke pelanggan. Pangowahan sing mbutuhake tooling anyar ditawarake kapisah.', deliveryTitle: 'Pangiriman', deliveryBody: 'Kita ngirim saindenging donya nganggo DHL utawa forwarder pilihan pelanggan. Ongkir, bea lan pajak ditawarake kapisah.', quoteTitle: 'Siap ngrembug proyek kacamata?', quoteBody: 'Kirim bahan pilihan, desain utawa gambar referensi lan syarat kustom. Lebokna SKU yen ngowahi model Kssmi.', reply: 'Biasane kita mangsuli sajrone siji dina kerja.',
  },
  ms: {
    eyebrow: 'Panduan projek label persendirian', title: 'Daripada Sampel kepada Pengeluaran', intro: 'Mulakan dengan model Kssmi sedia ada atau bangunkan cermin mata daripada idea anda. Lihat pilihan, proses kelulusan dan maklumat untuk bermula.',
    routesTitle: 'Dua cara untuk bermula', readyTitle: 'Sampel stok sedia ada', readyBody: 'Dibekalkan dengan bahan, warna, kanta dan spesifikasi asal. Logo standard boleh ditambah pada harga {logoFee} setiap model; butiran lain tidak boleh diubah.', customTitle: 'Pembangunan tersuai sepenuhnya', customBody: 'Ubah model sedia ada atau mulakan daripada lakaran, foto, konsep AI, sampel fizikal atau lukisan teknikal lengkap.',
    optionsTitle: 'Apa yang boleh disesuaikan?', optionsBody: 'Bahan, warna dan dimensi bingkai; bahan, warna, salutan dan fungsi kanta; kaedah dan lokasi logo; engsel, perkakasan, pad hidung, hujung tangkai, struktur, acuan dan perkakas.', packaging: 'Kami pakar dalam pembuatan cermin mata dan tidak menghasilkan pembungkusan runcit.',
    processTitle: 'Cara pembangunan tersuai', processSteps: ['Hantar idea', 'Semakan teknikal dan sebut harga', 'Paparan 2D dan pengesahan', 'Sampel fizikal', 'Kelulusan sampel', 'Pengeluaran dan kawalan kualiti', 'Semakan dan kelulusan sebelum penghantaran', 'Penghantaran dari pintu ke pintu'], processNote: 'Sehingga {revisions} pusingan semakan paparan 2D disertakan. Perubahan selepas sampel siap mungkin memerlukan caj pembangunan atau perkakas tambahan.',
    moqTimingTitle: 'MOQ dan tempoh anggaran', standardMoq: 'Kebanyakan bahan: {standardMoq} PCS setiap model', colorSplit: 'Sehingga {colors} warna, minimum {perColor} PCS setiap warna', tr90Moq: 'TR90: {tr90Moq} PCS setiap model', leadTimesTitle: 'Tempoh anggaran', readyLabel: 'Sampel stok', readyLogoLabel: 'Sampel stok dengan logo', renderingLabel: 'Paparan 2D', customSampleLabel: 'Sampel tersuai sepenuhnya', bulkLabel: 'Pengeluaran pukal', workingDays: 'hari bekerja', timingNote: 'Tempoh sampel tersuai bermula selepas 2D diluluskan. Pengeluaran bermula selepas sampel diluluskan dan deposit {deposit}% diterima. Tempoh sebenar mungkin berbeza.',
    termsTitle: 'Terma komersial dan penghantaran global', paymentTitle: 'Pembayaran', paymentBody: 'Sampel memerlukan bayaran pendahuluan {samplePayment}%. Pesanan pukal memerlukan deposit T/T {deposit}%, baki dibayar sebelum penghantaran.', samplesToolingTitle: 'Sampel dan perkakas', creditBody: 'Yuran sampel {readyPrice} dan {customMin}–{customMax} dikreditkan sepenuhnya kepada pesanan model sama apabila MOQ dipenuhi. Yuran logo {logoFee}, penghantaran dan cukai tidak dikreditkan.', toolingBody: 'Acuan dan perkakas yang dibayar pelanggan menjadi milik pelanggan. Perubahan yang memerlukan perkakas baharu disebut harga berasingan.', deliveryTitle: 'Penghantaran', deliveryBody: 'Kami menghantar ke seluruh dunia melalui DHL atau penghantar pilihan pelanggan. Kos pengangkutan, duti dan cukai disebut berasingan.', quoteTitle: 'Bersedia membincangkan projek cermin mata?', quoteBody: 'Hantar bahan pilihan, reka bentuk atau imej rujukan dan keperluan penyesuaian. Sertakan SKU apabila mengubah model Kssmi.', reply: 'Kami biasanya membalas dalam satu hari bekerja.',
  },
  tg: {
    eyebrow: 'Роҳнамои лоиҳаи бренди хусусӣ', title: 'Аз намуна то истеҳсол', intro: 'Аз модели мавҷудаи Kssmi оғоз кунед ё айнакро аз идеяи худ таҳия намоед. Имконот, тасдиқҳо ва маълумоти заруриро бинед.',
    routesTitle: 'Ду роҳи оғоз', readyTitle: 'Намунаи анборӣ', readyBody: 'Бо мавод, ранг, линза ва хусусиятҳои аслӣ дода мешавад. Логотипи стандартиро бо нархи {logoFee} барои ҳар модел илова кардан мумкин; дигар тағйирот иҷозат нест.', customTitle: 'Таҳияи пурраи фармоишӣ', customBody: 'Модели мавҷударо тағйир диҳед ё аз эскиз, акс, консепсияи AI, намунаи воқеӣ ё нақшаи пурраи техникӣ оғоз кунед.',
    optionsTitle: 'Чиро фармоишӣ кардан мумкин?', optionsBody: 'Мавод, ранг ва андозаи чорчӯба; мавод, ранг, рӯйпӯш ва вазифаи линза; усул ва ҷойи логотип; ҳалқа, қисмҳои металлӣ, такягоҳи бинӣ, нӯги даста, сохтор, қолаб ва таҷҳизот.', packaging: 'Мо ба истеҳсоли айнак тахассус дорем ва бастабандии чаканаро истеҳсол намекунем.',
    processTitle: 'Раванди таҳияи фармоишӣ', processSteps: ['Идеяро фиристед', 'Арзёбии муҳандисӣ ва нархнома', 'Тасвири 2D ва тасдиқ', 'Намунаи воқеӣ', 'Тасдиқи намуна', 'Истеҳсол ва назорати сифат', 'Санҷиш ва тасдиқ пеш аз фиристодан', 'Таҳвил то дари муштарӣ'], processNote: 'То {revisions} даври ислоҳи тасвири 2D дохил аст. Тағйирот пас аз омода шудани намуна метавонад хароҷоти иловагӣ талаб кунад.',
    moqTimingTitle: 'MOQ ва муҳлатҳои тахминӣ', standardMoq: 'Аксари мавод: {standardMoq} PCS барои ҳар модел', colorSplit: 'То {colors} ранг, ҳадди ақал {perColor} PCS барои ҳар ранг', tr90Moq: 'TR90: {tr90Moq} PCS барои ҳар модел', leadTimesTitle: 'Муҳлатҳои тахминӣ', readyLabel: 'Намунаи анборӣ', readyLogoLabel: 'Намунаи анборӣ бо логотип', renderingLabel: 'Тасвири 2D', customSampleLabel: 'Намунаи пурра фармоишӣ', bulkLabel: 'Истеҳсоли оммавӣ', workingDays: 'рӯзи корӣ', timingNote: 'Муҳлати намуна пас аз тасдиқи 2D оғоз мешавад. Истеҳсол пас аз тасдиқи намуна ва гирифтани пешпардохти {deposit}% оғоз мешавад. Муҳлат метавонад тағйир ёбад.',
    termsTitle: 'Шартҳои тиҷоратӣ ва таҳвили ҷаҳонӣ', paymentTitle: 'Пардохт', paymentBody: 'Намунаҳо {samplePayment}% пешпардохт талаб мекунанд. Барои истеҳсол пешпардохти T/T {deposit}% ва боқимонда пеш аз фиристодан пардохт мешавад.', samplesToolingTitle: 'Намуна ва қолаб', creditBody: 'Ҳаққи намунаҳои {readyPrice} ва {customMin}–{customMax} ҳангоми фармоиши ҳамон модел бо MOQ пурра ҳисоб карда мешавад. Ҳаққи логотип {logoFee}, интиқол ва андоз дохил нест.', toolingBody: 'Қолаб ва таҷҳизоте, ки муштарӣ пардохт кардааст, моли муштарӣ мебошад. Тағйироте, ки таҷҳизоти нав мехоҳад, алоҳида нархгузорӣ мешавад.', deliveryTitle: 'Таҳвил', deliveryBody: 'Мо бо DHL ё интиқолдиҳандаи интихобкардаи муштарӣ ба тамоми ҷаҳон мефиристем. Интиқол, боҷ ва андоз алоҳида ҳисоб мешавад.', quoteTitle: 'Омодаед лоиҳаи айнакро муҳокима кунед?', quoteBody: 'Маводи дилхоҳ, тарҳ ё тасвирҳои намунавӣ ва талаботи фармоиширо фиристед. Барои тағйири модели Kssmi SKU-ро илова кунед.', reply: 'Мо одатан дар як рӯзи корӣ ҷавоб медиҳем.',
  },
};
